/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceinfoendpointConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopeDeviceinfoendpointUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"

// GTLDeviceinfoendpoint - DeviceType
GTL_EXTERN NSString * const kGTLDeviceinfoendpoint_DeviceType_Android;  // "ANDROID"
GTL_EXTERN NSString * const kGTLDeviceinfoendpoint_DeviceType_IOS;  // "iOS"
