/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceinfoendpointDeviceInfo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLDeviceinfoendpointDeviceInfo (0 custom class methods, 12 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLDeviceinfoendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLDeviceinfoendpointDeviceInfo
//

@interface GTLDeviceinfoendpointDeviceInfo : GTLObject
@property (retain) NSNumber *bugfix;  // intValue
@property (retain) NSNumber *created;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) GTLDeviceinfoendpointKey *key;
@property (retain) NSNumber *lastLogin;  // longLongValue
@property (retain) NSNumber *loggedIn;  // boolValue
@property (retain) NSNumber *ownerId;  // longLongValue
@property (copy) NSString *phoneType;
@property (copy) NSString *registrationId;
@property (retain) NSNumber *update;  // intValue
@property (retain) NSNumber *updated;  // longLongValue
@property (retain) NSNumber *version;  // intValue
@end
