/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceinfoendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API

//#import "GTLDeviceinfoendpointConstants.m"
//
//#import "GTLDeviceinfoendpointCollectionResponseDeviceInfo.m"
//#import "GTLDeviceinfoendpointDeviceInfo.m"
//#import "GTLDeviceinfoendpointKey.m"
//
//#import "GTLQueryDeviceinfoendpoint.m"
//#import "GTLServiceDeviceinfoendpoint.m"


#import "GTLDeviceinfoendpointConstants.h"

#import "GTLDeviceinfoendpointCollectionResponseDeviceInfo.h"
#import "GTLDeviceinfoendpointDeviceInfo.h"
#import "GTLDeviceinfoendpointKey.h"

#import "GTLQueryDeviceinfoendpoint.h"
#import "GTLServiceDeviceinfoendpoint.h"