/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceinfoendpointDeviceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLDeviceinfoendpointDeviceInfo (0 custom class methods, 12 custom properties)

#import "GTLDeviceinfoendpointDeviceInfo.h"

#import "GTLDeviceinfoendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLDeviceinfoendpointDeviceInfo
//

@implementation GTLDeviceinfoendpointDeviceInfo
@dynamic bugfix, created, identifier, key, lastLogin, loggedIn, ownerId,
         phoneType, registrationId, update, updated, version;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
