/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceinfoendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API

#import "GTLDeviceinfoendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeDeviceinfoendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLDeviceinfoendpoint - DeviceType
NSString * const kGTLDeviceinfoendpoint_DeviceType_Android = @"ANDROID";
NSString * const kGTLDeviceinfoendpoint_DeviceType_IOS     = @"iOS";
