/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventcommentendpointEventComment.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventcommentendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLEventcommentendpointEventComment (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLEventcommentendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLEventcommentendpointEventComment
//

@interface GTLEventcommentendpointEventComment : GTLObject
@property (retain) NSNumber *commenterId;  // longLongValue
@property (retain) NSNumber *created;  // longLongValue
@property (retain) NSNumber *eventId;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) GTLEventcommentendpointKey *key;
@property (copy) NSString *text;
@property (retain) NSNumber *updated;  // longLongValue
@end
