/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventcommentendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventcommentendpoint/v1
// Description:
//   This is an API

//#import "GTLEventcommentendpointConstants.m"
//
//#import "GTLEventcommentendpointCollectionResponseEventComment.m"
//#import "GTLEventcommentendpointEventComment.m"
//#import "GTLEventcommentendpointKey.m"
//
//#import "GTLQueryEventcommentendpoint.m"
//#import "GTLServiceEventcommentendpoint.m"

#import "GTLEventcommentendpointConstants.h"

#import "GTLEventcommentendpointCollectionResponseEventComment.h"
#import "GTLEventcommentendpointEventComment.h"
#import "GTLEventcommentendpointKey.h"

#import "GTLQueryEventcommentendpoint.h"
#import "GTLServiceEventcommentendpoint.h"