/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagendpoint/v1
// Description:
//   This is an API

//#import "GTLEventtagendpointConstants.m"
//
//#import "GTLEventtagendpointCollectionResponseEventTag.m"
//#import "GTLEventtagendpointEventTag.m"
//#import "GTLEventtagendpointKey.m"
//
//#import "GTLQueryEventtagendpoint.m"
//#import "GTLServiceEventtagendpoint.m"

#import "GTLEventtagendpointConstants.h"

#import "GTLEventtagendpointCollectionResponseEventTag.h"
#import "GTLEventtagendpointEventTag.h"
#import "GTLEventtagendpointKey.h"

#import "GTLQueryEventtagendpoint.h"
#import "GTLServiceEventtagendpoint.h"