/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagfollowendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagfollowendpoint/v1
// Description:
//   This is an API

//#import "GTLEventtagfollowendpointConstants.m"
//
//#import "GTLEventtagfollowendpointCollectionResponseEventTagFollow.m"
//#import "GTLEventtagfollowendpointEventTagFollow.m"
//#import "GTLEventtagfollowendpointKey.m"
//
//#import "GTLQueryEventtagfollowendpoint.m"
//#import "GTLServiceEventtagfollowendpoint.m"

#import "GTLEventtagfollowendpointConstants.h"

#import "GTLEventtagfollowendpointCollectionResponseEventTagFollow.h"
#import "GTLEventtagfollowendpointEventTagFollow.h"
#import "GTLEventtagfollowendpointKey.h"

#import "GTLQueryEventtagfollowendpoint.h"
#import "GTLServiceEventtagfollowendpoint.h"