/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventcommentendpointEventComment.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventcommentendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLEventcommentendpointEventComment (0 custom class methods, 7 custom properties)

#import "GTLEventcommentendpointEventComment.h"

#import "GTLEventcommentendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLEventcommentendpointEventComment
//

@implementation GTLEventcommentendpointEventComment
@dynamic commenterId, created, eventId, identifier, key, text, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
