/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventcommentendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventcommentendpoint/v1
// Description:
//   This is an API

#import "GTLEventcommentendpointConstants.h"

#import "GTLEventcommentendpointCollectionResponseEventComment.h"
#import "GTLEventcommentendpointEventComment.h"
#import "GTLEventcommentendpointKey.h"

#import "GTLQueryEventcommentendpoint.h"
#import "GTLServiceEventcommentendpoint.h"
