/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagfollowendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagfollowendpoint/v1
// Description:
//   This is an API

#import "GTLEventtagfollowendpointConstants.h"

#import "GTLEventtagfollowendpointCollectionResponseEventTagFollow.h"
#import "GTLEventtagfollowendpointEventTagFollow.h"
#import "GTLEventtagfollowendpointKey.h"

#import "GTLQueryEventtagfollowendpoint.h"
#import "GTLServiceEventtagfollowendpoint.h"
