/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagfollowendpointCollectionResponseEventTagFollow.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagfollowendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLEventtagfollowendpointCollectionResponseEventTagFollow (0 custom class methods, 2 custom properties)

#import "GTLEventtagfollowendpointCollectionResponseEventTagFollow.h"

#import "GTLEventtagfollowendpointEventTagFollow.h"

// ----------------------------------------------------------------------------
//
//   GTLEventtagfollowendpointCollectionResponseEventTagFollow
//

@implementation GTLEventtagfollowendpointCollectionResponseEventTagFollow
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLEventtagfollowendpointEventTagFollow class]
                                forKey:@"items"];
  return map;
}

@end
