/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventcommentendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventcommentendpoint/v1
// Description:
//   This is an API

#import "GTLEventcommentendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeEventcommentendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
