/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPhotoinfoendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   photoinfoendpoint/v1
// Description:
//   This is an API

//#import "GTLPhotoinfoendpointConstants.m"
//
//#import "GTLPhotoinfoendpointCollectionResponsePhotoInfo.m"
//#import "GTLPhotoinfoendpointKey.m"
//#import "GTLPhotoinfoendpointPhotoInfo.m"
//
//#import "GTLQueryPhotoinfoendpoint.m"
//#import "GTLServicePhotoinfoendpoint.m"

#import "GTLPhotoinfoendpointConstants.h"

#import "GTLPhotoinfoendpointCollectionResponsePhotoInfo.h"
#import "GTLPhotoinfoendpointKey.h"
#import "GTLPhotoinfoendpointPhotoInfo.h"

#import "GTLQueryPhotoinfoendpoint.h"
#import "GTLServicePhotoinfoendpoint.h"