/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPhotoinfoendpointKey.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   photoinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPhotoinfoendpointKey (0 custom class methods, 7 custom properties)

#import "GTLPhotoinfoendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLPhotoinfoendpointKey
//

@implementation GTLPhotoinfoendpointKey
@dynamic appId, complete, identifier, kind, name, namespaceProperty, parent;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"id", @"identifier",
      @"namespace", @"namespaceProperty",
      nil];
  return map;
}

@end
