/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPhotoinfoendpointPhotoInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   photoinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPhotoinfoendpointPhotoInfo (0 custom class methods, 5 custom properties)

#import "GTLPhotoinfoendpointPhotoInfo.h"

#import "GTLPhotoinfoendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLPhotoinfoendpointPhotoInfo
//

@implementation GTLPhotoinfoendpointPhotoInfo
@dynamic blobKey, identifier, key, ownerEmail, url;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
