/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppafeedbackendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppafeedbackendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppafeedbackendpoint (5 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLZeppafeedbackendpointZeppaFeedback;

@interface GTLQueryZeppafeedbackendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *cursor;
@property (copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) NSInteger limit;
@property (copy) NSString *ordering;
@property (copy) NSString *parameterDeclaration;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryZeppafeedbackendpoint object.

// Method: zeppafeedbackendpoint.getZeppaFeedback
//  Authorization scope(s):
//   kGTLAuthScopeZeppafeedbackendpointUserinfoEmail
// Fetches a GTLZeppafeedbackendpointZeppaFeedback.
+ (id)queryForGetZeppaFeedbackWithIdentifier:(long long)identifier;

// Method: zeppafeedbackendpoint.insertZeppaFeedback
//  Authorization scope(s):
//   kGTLAuthScopeZeppafeedbackendpointUserinfoEmail
// Fetches a GTLZeppafeedbackendpointZeppaFeedback.
+ (id)queryForInsertZeppaFeedbackWithObject:(GTLZeppafeedbackendpointZeppaFeedback *)object;

// Method: zeppafeedbackendpoint.listZeppaFeedback
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//   parameterDeclaration: NSString
//  Authorization scope(s):
//   kGTLAuthScopeZeppafeedbackendpointUserinfoEmail
// Fetches a GTLZeppafeedbackendpointCollectionResponseZeppaFeedback.
+ (id)queryForListZeppaFeedback;

// Method: zeppafeedbackendpoint.removeZeppaFeedback
//  Authorization scope(s):
//   kGTLAuthScopeZeppafeedbackendpointUserinfoEmail
+ (id)queryForRemoveZeppaFeedbackWithIdentifier:(long long)identifier;

// Method: zeppafeedbackendpoint.updateZeppaFeedback
//  Authorization scope(s):
//   kGTLAuthScopeZeppafeedbackendpointUserinfoEmail
// Fetches a GTLZeppafeedbackendpointZeppaFeedback.
+ (id)queryForUpdateZeppaFeedbackWithObject:(GTLZeppafeedbackendpointZeppaFeedback *)object;

@end
