/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppanotificationendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppanotificationendpoint (5 custom class methods, 6 custom properties)

#import "GTLQueryZeppanotificationendpoint.h"

#import "GTLZeppanotificationendpointCollectionResponseZeppaNotification.h"
#import "GTLZeppanotificationendpointZeppaNotification.h"

@implementation GTLQueryZeppanotificationendpoint

@dynamic cursor, fields, filter, identifier, limit, ordering;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryZeppanotificationendpoint object.

+ (id)queryForGetZeppaNotificationWithIdentifier:(long long)identifier {
  NSString *methodName = @"zeppanotificationendpoint.getZeppaNotification";
  GTLQueryZeppanotificationendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLZeppanotificationendpointZeppaNotification class];
  return query;
}

+ (id)queryForInsertZeppaNotificationWithObject:(GTLZeppanotificationendpointZeppaNotification *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppanotificationendpoint.insertZeppaNotification";
  GTLQueryZeppanotificationendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppanotificationendpointZeppaNotification class];
  return query;
}

+ (id)queryForListZeppaNotification {
  NSString *methodName = @"zeppanotificationendpoint.listZeppaNotification";
  GTLQueryZeppanotificationendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLZeppanotificationendpointCollectionResponseZeppaNotification class];
  return query;
}

+ (id)queryForRemoveZeppaNotificationWithIdentifier:(long long)identifier {
  NSString *methodName = @"zeppanotificationendpoint.removeZeppaNotification";
  GTLQueryZeppanotificationendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  return query;
}

+ (id)queryForUpdateZeppaNotificationWithObject:(GTLZeppanotificationendpointZeppaNotification *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppanotificationendpoint.updateZeppaNotification";
  GTLQueryZeppanotificationendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppanotificationendpointZeppaNotification class];
  return query;
}

@end
