/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryDeviceinfoendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryDeviceinfoendpoint (5 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLDeviceinfoendpointDeviceInfo;

@interface GTLQueryDeviceinfoendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *cursor;
@property (copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) NSInteger limit;
@property (copy) NSString *ordering;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryDeviceinfoendpoint object.

// Method: deviceinfoendpoint.getDeviceInfo
//  Authorization scope(s):
//   kGTLAuthScopeDeviceinfoendpointUserinfoEmail
// Fetches a GTLDeviceinfoendpointDeviceInfo.
+ (id)queryForGetDeviceInfoWithIdentifier:(long long)identifier;

// Method: deviceinfoendpoint.insertDeviceInfo
//  Authorization scope(s):
//   kGTLAuthScopeDeviceinfoendpointUserinfoEmail
// Fetches a GTLDeviceinfoendpointDeviceInfo.
+ (id)queryForInsertDeviceInfoWithObject:(GTLDeviceinfoendpointDeviceInfo *)object;

// Method: deviceinfoendpoint.listDeviceInfo
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeDeviceinfoendpointUserinfoEmail
// Fetches a GTLDeviceinfoendpointCollectionResponseDeviceInfo.
+ (id)queryForListDeviceInfo;

// Method: deviceinfoendpoint.removeDeviceInfo
//  Authorization scope(s):
//   kGTLAuthScopeDeviceinfoendpointUserinfoEmail
+ (id)queryForRemoveDeviceInfoWithObject:(GTLDeviceinfoendpointDeviceInfo *)object;

// Method: deviceinfoendpoint.updateDeviceInfo
//  Authorization scope(s):
//   kGTLAuthScopeDeviceinfoendpointUserinfoEmail
// Fetches a GTLDeviceinfoendpointDeviceInfo.
+ (id)queryForUpdateDeviceInfoWithObject:(GTLDeviceinfoendpointDeviceInfo *)object;

@end
