/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppauserendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppauserendpoint (6 custom class methods, 7 custom properties)

#import "GTLQueryZeppauserendpoint.h"

#import "GTLZeppauserendpointCollectionResponseZeppaUser.h"
#import "GTLZeppauserendpointZeppaUser.h"

@implementation GTLQueryZeppauserendpoint

@dynamic cursor, fields, filter, identifier, limit, ordering, userId;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryZeppauserendpoint object.

+ (id)queryForFetchCurrentZeppaUser {
  NSString *methodName = @"zeppauserendpoint.fetchCurrentZeppaUser";
  GTLQueryZeppauserendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLZeppauserendpointZeppaUser class];
  return query;
}

+ (id)queryForGetZeppaUserWithUserId:(long long)userId {
  NSString *methodName = @"zeppauserendpoint.getZeppaUser";
  GTLQueryZeppauserendpoint *query = [self queryWithMethodName:methodName];
  query.userId = userId;
  query.expectedObjectClass = [GTLZeppauserendpointZeppaUser class];
  return query;
}

+ (id)queryForInsertZeppaUserWithObject:(GTLZeppauserendpointZeppaUser *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppauserendpoint.insertZeppaUser";
  GTLQueryZeppauserendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppauserendpointZeppaUser class];
  return query;
}

+ (id)queryForListZeppaUser {
  NSString *methodName = @"zeppauserendpoint.listZeppaUser";
  GTLQueryZeppauserendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLZeppauserendpointCollectionResponseZeppaUser class];
  return query;
}

+ (id)queryForRemoveZeppaUserWithIdentifier:(long long)identifier {
  NSString *methodName = @"zeppauserendpoint.removeZeppaUser";
  GTLQueryZeppauserendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  return query;
}

+ (id)queryForUpdateZeppaUserWithObject:(GTLZeppauserendpointZeppaUser *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppauserendpoint.updateZeppaUser";
  GTLQueryZeppauserendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppauserendpointZeppaUser class];
  return query;
}

@end
