/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventendpointCollectionResponseZeppaEvent.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaeventendpointCollectionResponseZeppaEvent (0 custom class methods, 2 custom properties)

#import "GTLZeppaeventendpointCollectionResponseZeppaEvent.h"

#import "GTLZeppaeventendpointZeppaEvent.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaeventendpointCollectionResponseZeppaEvent
//

@implementation GTLZeppaeventendpointCollectionResponseZeppaEvent
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLZeppaeventendpointZeppaEvent class]
                                forKey:@"items"];
  return map;
}

@end
