/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API

#import "GTLZeppauserendpointConstants.h"

#import "GTLZeppauserendpointCollectionResponseZeppaUser.h"
#import "GTLZeppauserendpointKey.h"
#import "GTLZeppauserendpointZeppaUser.h"
#import "GTLZeppauserendpointZeppaUserInfo.h"

#import "GTLQueryZeppauserendpoint.h"
#import "GTLServiceZeppauserendpoint.h"
