/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserendpointCollectionResponseZeppaUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppauserendpointCollectionResponseZeppaUser (0 custom class methods, 2 custom properties)

#import "GTLZeppauserendpointCollectionResponseZeppaUser.h"

#import "GTLZeppauserendpointZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppauserendpointCollectionResponseZeppaUser
//

@implementation GTLZeppauserendpointCollectionResponseZeppaUser
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLZeppauserendpointZeppaUser class]
                                forKey:@"items"];
  return map;
}

@end
