/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API

// Commented out and switched to .h imports trying to resolve linker error
//#import "GTLZeppauserendpointConstants.m"
//
//#import "GTLZeppauserendpointCollectionResponseZeppaUser.m"
//#import "GTLZeppauserendpointKey.m"
//#import "GTLZeppauserendpointZeppaUser.m"
//#import "GTLZeppauserendpointZeppaUserInfo.m"
//
//#import "GTLQueryZeppauserendpoint.m"
//#import "GTLServiceZeppauserendpoint.m"

#import "GTLZeppauserendpointConstants.h"

#import "GTLZeppauserendpointCollectionResponseZeppaUser.h"
#import "GTLZeppauserendpointKey.h"
#import "GTLZeppauserendpointZeppaUser.h"
#import "GTLZeppauserendpointZeppaUserInfo.h"

#import "GTLQueryZeppauserendpoint.h"
#import "GTLServiceZeppauserendpoint.h"