/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventtouserrelationshipendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API

//#import "GTLZeppaeventtouserrelationshipendpointConstants.m"
//
//#import "GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship.m"
//#import "GTLZeppaeventtouserrelationshipendpointKey.m"
//#import "GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.m"
//
//#import "GTLQueryZeppaeventtouserrelationshipendpoint.m"
//#import "GTLServiceZeppaeventtouserrelationshipendpoint.m"

#import "GTLZeppaeventtouserrelationshipendpointConstants.h"

#import "GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship.h"
#import "GTLZeppaeventtouserrelationshipendpointKey.h"
#import "GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.h"

#import "GTLQueryZeppaeventtouserrelationshipendpoint.h"
#import "GTLServiceZeppaeventtouserrelationshipendpoint.h"