/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppafeedbackendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppafeedbackendpoint/v1
// Description:
//   This is an API

//#import "GTLZeppafeedbackendpointConstants.m"
//
//#import "GTLZeppafeedbackendpointCollectionResponseZeppaFeedback.m"
//#import "GTLZeppafeedbackendpointKey.m"
//#import "GTLZeppafeedbackendpointZeppaFeedback.m"
//
//#import "GTLQueryZeppafeedbackendpoint.m"
//#import "GTLServiceZeppafeedbackendpoint.m"

#import "GTLZeppafeedbackendpointConstants.h"

#import "GTLZeppafeedbackendpointCollectionResponseZeppaFeedback.h"
#import "GTLZeppafeedbackendpointKey.h"
#import "GTLZeppafeedbackendpointZeppaFeedback.h"

#import "GTLQueryZeppafeedbackendpoint.h"
#import "GTLServiceZeppafeedbackendpoint.h"