/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppafeedbackendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppafeedbackendpoint/v1
// Description:
//   This is an API

#import "GTLZeppafeedbackendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppafeedbackendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLZeppafeedbackendpoint - DeviceType
NSString * const kGTLZeppafeedbackendpoint_DeviceType_Android = @"ANDROID";
NSString * const kGTLZeppafeedbackendpoint_DeviceType_IOS     = @"iOS";
