/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppanotificationendpointConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopeZeppanotificationendpointUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"

// GTLZeppanotificationendpoint - NotificationType
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_CommentOnPost;  // "COMMENT_ON_POST"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_DirectInvite;  // "DIRECT_INVITE"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_EventCanceled;  // "EVENT_CANCELED"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_EventRecommendation;  // "EVENT_RECOMMENDATION"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_EventUpdated;  // "EVENT_UPDATED"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_MingleAccepted;  // "MINGLE_ACCEPTED"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_MingleRequest;  // "MINGLE_REQUEST"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_UserJoined;  // "USER_JOINED"
GTL_EXTERN NSString * const kGTLZeppanotificationendpoint_NotificationType_UserLeaving;  // "USER_LEAVING"
