/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API

#import "GTLZeppauserendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppauserendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
