/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserinfoendpointZeppaUserInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppauserinfoendpointZeppaUserInfo (0 custom class methods, 9 custom properties)

#import "GTLZeppauserinfoendpointZeppaUserInfo.h"

#import "GTLZeppauserinfoendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppauserinfoendpointZeppaUserInfo
//

@implementation GTLZeppauserinfoendpointZeppaUserInfo
@dynamic created, familyName, givenName, googleAccountEmail, identifier,
         imageUrl, key, primaryUnformattedNumber, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
