/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserinfoendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserinfoendpoint/v1
// Description:
//   This is an API

//#import "GTLZeppauserinfoendpointConstants.m"
//
//#import "GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo.m"
//#import "GTLZeppauserinfoendpointKey.m"
//#import "GTLZeppauserinfoendpointZeppaUserInfo.m"
//
//#import "GTLQueryZeppauserinfoendpoint.m"
//#import "GTLServiceZeppauserinfoendpoint.m"

#import "GTLZeppauserinfoendpointConstants.h"

#import "GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo.h"
#import "GTLZeppauserinfoendpointKey.h"
#import "GTLZeppauserinfoendpointZeppaUserInfo.h"

#import "GTLQueryZeppauserinfoendpoint.h"
#import "GTLServiceZeppauserinfoendpoint.h"