/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppanotificationendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API

#import "GTLZeppanotificationendpointConstants.h"

#import "GTLZeppanotificationendpointCollectionResponseZeppaNotification.h"
#import "GTLZeppanotificationendpointKey.h"
#import "GTLZeppanotificationendpointZeppaNotification.h"

#import "GTLQueryZeppanotificationendpoint.h"
#import "GTLServiceZeppanotificationendpoint.h"
