/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppafeedbackendpointZeppaFeedback.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppafeedbackendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppafeedbackendpointZeppaFeedback (0 custom class methods, 10 custom properties)

#import "GTLZeppafeedbackendpointZeppaFeedback.h"

#import "GTLZeppafeedbackendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppafeedbackendpointZeppaFeedback
//

@implementation GTLZeppafeedbackendpointZeppaFeedback
@dynamic created, deviceType, feedback, identifier, key, rating, releaseCode,
         subject, updated, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
