/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventendpointZeppaEvent.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaeventendpointZeppaEvent (0 custom class methods, 18 custom properties)

#import "GTLZeppaeventendpointZeppaEvent.h"

#import "GTLZeppaeventendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaeventendpointZeppaEvent
//

@implementation GTLZeppaeventendpointZeppaEvent
@dynamic created, descriptionProperty, displayLocation, end,
         googleCalendarEventId, googleCalendarId, guestsMayInvite, hostId,
         iCalUID, identifier, invitedUserIds, key, mapsLocation, privacy, start,
         tagIds, title, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [NSNumber class], @"invitedUserIds",
      [NSNumber class], @"tagIds",
      nil];
  return map;
}

@end
