/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppafeedbackendpointZeppaFeedback.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppafeedbackendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppafeedbackendpointZeppaFeedback (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppafeedbackendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLZeppafeedbackendpointZeppaFeedback
//

@interface GTLZeppafeedbackendpointZeppaFeedback : GTLObject
@property (retain) NSNumber *created;  // longLongValue
@property (copy) NSString *deviceType;
@property (copy) NSString *feedback;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) GTLZeppafeedbackendpointKey *key;
@property (retain) NSNumber *rating;  // doubleValue
@property (copy) NSString *releaseCode;
@property (copy) NSString *subject;
@property (retain) NSNumber *updated;  // longLongValue
@property (retain) NSNumber *userId;  // longLongValue
@end
