/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserinfoendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserinfoendpoint/v1
// Description:
//   This is an API

#import "GTLZeppauserinfoendpointConstants.h"

#import "GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo.h"
#import "GTLZeppauserinfoendpointKey.h"
#import "GTLZeppauserinfoendpointZeppaUserInfo.h"

#import "GTLQueryZeppauserinfoendpoint.h"
#import "GTLServiceZeppauserinfoendpoint.h"
