/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventendpoint/v1
// Description:
//   This is an API

//#import "GTLZeppaeventendpointConstants.m"
//
//#import "GTLZeppaeventendpointCollectionResponseZeppaEvent.m"
//#import "GTLZeppaeventendpointKey.m"
//#import "GTLZeppaeventendpointZeppaEvent.m"
//
//#import "GTLQueryZeppaeventendpoint.m"
//#import "GTLServiceZeppaeventendpoint.m"

#import "GTLZeppaeventendpointConstants.h"

#import "GTLZeppaeventendpointCollectionResponseZeppaEvent.h"
#import "GTLZeppaeventendpointKey.h"
#import "GTLZeppaeventendpointZeppaEvent.h"

#import "GTLQueryZeppaeventendpoint.h"
#import "GTLServiceZeppaeventendpoint.h"
