/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppausertouserrelationshipendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API

//#import "GTLZeppausertouserrelationshipendpointConstants.m"
//
//#import "GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship.m"
//#import "GTLZeppausertouserrelationshipendpointKey.m"
//#import "GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.m"
//
//#import "GTLQueryZeppausertouserrelationshipendpoint.m"
//#import "GTLServiceZeppausertouserrelationshipendpoint.m"

#import "GTLZeppausertouserrelationshipendpointConstants.h"

#import "GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship.h"
#import "GTLZeppausertouserrelationshipendpointKey.h"
#import "GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.h"

#import "GTLQueryZeppausertouserrelationshipendpoint.h"
#import "GTLServiceZeppausertouserrelationshipendpoint.h"