/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppanotificationendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API

#import "GTLZeppanotificationendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppanotificationendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLZeppanotificationendpoint - NotificationType
NSString * const kGTLZeppanotificationendpoint_NotificationType_CommentOnPost = @"COMMENT_ON_POST";
NSString * const kGTLZeppanotificationendpoint_NotificationType_DirectInvite = @"DIRECT_INVITE";
NSString * const kGTLZeppanotificationendpoint_NotificationType_EventCanceled = @"EVENT_CANCELED";
NSString * const kGTLZeppanotificationendpoint_NotificationType_EventRecommendation = @"EVENT_RECOMMENDATION";
NSString * const kGTLZeppanotificationendpoint_NotificationType_EventUpdated = @"EVENT_UPDATED";
NSString * const kGTLZeppanotificationendpoint_NotificationType_MingleAccepted = @"MINGLE_ACCEPTED";
NSString * const kGTLZeppanotificationendpoint_NotificationType_MingleRequest = @"MINGLE_REQUEST";
NSString * const kGTLZeppanotificationendpoint_NotificationType_UserJoined = @"USER_JOINED";
NSString * const kGTLZeppanotificationendpoint_NotificationType_UserLeaving = @"USER_LEAVING";
