/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppanotificationendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API

//#import "GTLZeppanotificationendpointConstants.m"
//
//#import "GTLZeppanotificationendpointCollectionResponseZeppaNotification.m"
//#import "GTLZeppanotificationendpointKey.m"
//#import "GTLZeppanotificationendpointZeppaNotification.m"
//
//#import "GTLQueryZeppanotificationendpoint.m"
//#import "GTLServiceZeppanotificationendpoint.m"

#import "GTLZeppanotificationendpointConstants.h"

#import "GTLZeppanotificationendpointCollectionResponseZeppaNotification.h"
#import "GTLZeppanotificationendpointKey.h"
#import "GTLZeppanotificationendpointZeppaNotification.h"

#import "GTLQueryZeppanotificationendpoint.h"
#import "GTLServiceZeppanotificationendpoint.h"