/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppausertouserrelationshipendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API

#import "GTLZeppausertouserrelationshipendpointConstants.h"

#import "GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship.h"
#import "GTLZeppausertouserrelationshipendpointKey.h"
#import "GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.h"

#import "GTLQueryZeppausertouserrelationshipendpoint.h"
#import "GTLServiceZeppausertouserrelationshipendpoint.h"
