/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppanotificationendpointZeppaNotification.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppanotificationendpointZeppaNotification (0 custom class methods, 12 custom properties)

#import "GTLZeppanotificationendpointZeppaNotification.h"

#import "GTLZeppanotificationendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppanotificationendpointZeppaNotification
//

@implementation GTLZeppanotificationendpointZeppaNotification
@dynamic created, eventId, expires, extraMessage, hasSeen, identifier, key,
         recipientId, senderId, type, updated, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
