/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppausertouserrelationshipendpointConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopeZeppausertouserrelationshipendpointUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"

// GTLZeppausertouserrelationshipendpoint - UserRelationshipType
GTL_EXTERN NSString * const kGTLZeppausertouserrelationshipendpoint_UserRelationshipType_Mingling;  // "MINGLING"
GTL_EXTERN NSString * const kGTLZeppausertouserrelationshipendpoint_UserRelationshipType_PendingRequest;  // "PENDING_REQUEST"
