/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventtouserrelationshipendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API

#import "GTLZeppaeventtouserrelationshipendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppaeventtouserrelationshipendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
