/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship (0 custom class methods, 2 custom properties)

#import "GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship.h"

#import "GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship
//

@implementation GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship class]
                                forKey:@"items"];
  return map;
}

@end
