/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceinfoendpointCollectionResponseDeviceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLDeviceinfoendpointCollectionResponseDeviceInfo (0 custom class methods, 2 custom properties)

#import "GTLDeviceinfoendpointCollectionResponseDeviceInfo.h"

#import "GTLDeviceinfoendpointDeviceInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLDeviceinfoendpointCollectionResponseDeviceInfo
//

@implementation GTLDeviceinfoendpointCollectionResponseDeviceInfo
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLDeviceinfoendpointDeviceInfo class]
  };
  return map;
}

@end
