/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceinfoendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceinfoendpoint/v1
// Description:
//   This is an API

#import "GTLDeviceinfoendpointConstants.h"

#import "GTLDeviceinfoendpointCollectionResponseDeviceInfo.h"
#import "GTLDeviceinfoendpointDeviceInfo.h"
#import "GTLDeviceinfoendpointKey.h"

#import "GTLQueryDeviceinfoendpoint.h"
#import "GTLServiceDeviceinfoendpoint.h"
