/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventcommentendpointCollectionResponseEventComment.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventcommentendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLEventcommentendpointCollectionResponseEventComment (0 custom class methods, 2 custom properties)

#import "GTLEventcommentendpointCollectionResponseEventComment.h"

#import "GTLEventcommentendpointEventComment.h"

// ----------------------------------------------------------------------------
//
//   GTLEventcommentendpointCollectionResponseEventComment
//

@implementation GTLEventcommentendpointCollectionResponseEventComment
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLEventcommentendpointEventComment class]
  };
  return map;
}

@end
