/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagendpoint/v1
// Description:
//   This is an API

#import "GTLEventtagendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeEventtagendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
