/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagendpointEventTag.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLEventtagendpointEventTag (0 custom class methods, 6 custom properties)

#import "GTLEventtagendpointEventTag.h"

#import "GTLEventtagendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLEventtagendpointEventTag
//

@implementation GTLEventtagendpointEventTag
@dynamic created, identifier, key, ownerId, tagText, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
