/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagendpointCollectionResponseEventTag.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLEventtagendpointCollectionResponseEventTag (0 custom class methods, 2 custom properties)

#import "GTLEventtagendpointCollectionResponseEventTag.h"

#import "GTLEventtagendpointEventTag.h"

// ----------------------------------------------------------------------------
//
//   GTLEventtagendpointCollectionResponseEventTag
//

@implementation GTLEventtagendpointCollectionResponseEventTag
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLEventtagendpointEventTag class]
  };
  return map;
}

@end
