/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagfollowendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagfollowendpoint/v1
// Description:
//   This is an API

#import "GTLEventtagfollowendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeEventtagfollowendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
