/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventtagendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagendpoint/v1
// Description:
//   This is an API

#import "GTLEventtagendpointConstants.h"

#import "GTLEventtagendpointCollectionResponseEventTag.h"
#import "GTLEventtagendpointEventTag.h"
#import "GTLEventtagendpointKey.h"

#import "GTLQueryEventtagendpoint.h"
#import "GTLServiceEventtagendpoint.h"
