/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPhotoinfoendpointPhotoInfo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   photoinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPhotoinfoendpointPhotoInfo (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPhotoinfoendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLPhotoinfoendpointPhotoInfo
//

@interface GTLPhotoinfoendpointPhotoInfo : GTLObject
@property (nonatomic, copy) NSString *blobKey;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLPhotoinfoendpointKey *key;
@property (nonatomic, copy) NSString *ownerEmail;
@property (nonatomic, copy) NSString *url;
@end
