/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPhotoinfoendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   photoinfoendpoint/v1
// Description:
//   This is an API

#import "GTLPhotoinfoendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopePhotoinfoendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
