/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLPhotoinfoendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   photoinfoendpoint/v1
// Description:
//   This is an API

#import "GTLPhotoinfoendpointConstants.h"

#import "GTLPhotoinfoendpointCollectionResponsePhotoInfo.h"
#import "GTLPhotoinfoendpointKey.h"
#import "GTLPhotoinfoendpointPhotoInfo.h"

#import "GTLQueryPhotoinfoendpoint.h"
#import "GTLServicePhotoinfoendpoint.h"
