/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppaeventtouserrelationshipendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppaeventtouserrelationshipendpoint (5 custom class methods, 6 custom properties)

#import "GTLQueryZeppaeventtouserrelationshipendpoint.h"

#import "GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship.h"
#import "GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.h"

@implementation GTLQueryZeppaeventtouserrelationshipendpoint

@dynamic cursor, fields, filter, identifier, limit, ordering;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

#pragma mark - Service level methods
// These create a GTLQueryZeppaeventtouserrelationshipendpoint object.

+ (instancetype)queryForGetZeppaEventToUserRelationshipWithIdentifier:(long long)identifier {
  NSString *methodName = @"zeppaeventtouserrelationshipendpoint.getZeppaEventToUserRelationship";
  GTLQueryZeppaeventtouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship class];
  return query;
}

+ (instancetype)queryForInsertZeppaEventToUserRelationshipWithObject:(GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppaeventtouserrelationshipendpoint.insertZeppaEventToUserRelationship";
  GTLQueryZeppaeventtouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship class];
  return query;
}

+ (instancetype)queryForListZeppaEventToUserRelationship {
  NSString *methodName = @"zeppaeventtouserrelationshipendpoint.listZeppaEventToUserRelationship";
  GTLQueryZeppaeventtouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship class];
  return query;
}

+ (instancetype)queryForRemoveZeppaEventToUserRelationshipWithIdentifier:(long long)identifier {
  NSString *methodName = @"zeppaeventtouserrelationshipendpoint.removeZeppaEventToUserRelationship";
  GTLQueryZeppaeventtouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  return query;
}

+ (instancetype)queryForUpdateZeppaEventToUserRelationshipWithObject:(GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppaeventtouserrelationshipendpoint.updateZeppaEventToUserRelationship";
  GTLQueryZeppaeventtouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship class];
  return query;
}

@end
