/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryEventtagendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryEventtagendpoint (4 custom class methods, 7 custom properties)

#import "GTLQueryEventtagendpoint.h"

#import "GTLEventtagendpointCollectionResponseEventTag.h"
#import "GTLEventtagendpointEventTag.h"

@implementation GTLQueryEventtagendpoint

@dynamic cursor, fields, filter, identifier, limit, ordering, tagId;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

#pragma mark - Service level methods
// These create a GTLQueryEventtagendpoint object.

+ (instancetype)queryForGetEventTagWithIdentifier:(long long)identifier {
  NSString *methodName = @"eventtagendpoint.getEventTag";
  GTLQueryEventtagendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLEventtagendpointEventTag class];
  return query;
}

+ (instancetype)queryForInsertEventTagWithObject:(GTLEventtagendpointEventTag *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"eventtagendpoint.insertEventTag";
  GTLQueryEventtagendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLEventtagendpointEventTag class];
  return query;
}

+ (instancetype)queryForListEventTag {
  NSString *methodName = @"eventtagendpoint.listEventTag";
  GTLQueryEventtagendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLEventtagendpointCollectionResponseEventTag class];
  return query;
}

+ (instancetype)queryForRemoveEventTagWithTagId:(long long)tagId {
  NSString *methodName = @"eventtagendpoint.removeEventTag";
  GTLQueryEventtagendpoint *query = [self queryWithMethodName:methodName];
  query.tagId = tagId;
  return query;
}

@end
