/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppauserendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppauserendpoint (6 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLZeppauserendpointZeppaUser;

@interface GTLQueryZeppauserendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) NSInteger limit;
@property (nonatomic, copy) NSString *ordering;
@property (nonatomic, assign) long long userId;

#pragma mark - Service level methods
// These create a GTLQueryZeppauserendpoint object.

// Method: zeppauserendpoint.fetchCurrentZeppaUser
//  Authorization scope(s):
//   kGTLAuthScopeZeppauserendpointUserinfoEmail
// Fetches a GTLZeppauserendpointZeppaUser.
+ (instancetype)queryForFetchCurrentZeppaUserWithEmail:(NSString *)email;

// Method: zeppauserendpoint.getZeppaUser
//  Authorization scope(s):
//   kGTLAuthScopeZeppauserendpointUserinfoEmail
// Fetches a GTLZeppauserendpointZeppaUser.
+ (instancetype)queryForGetZeppaUserWithUserId:(long long)userId;

// Method: zeppauserendpoint.insertZeppaUser
//  Authorization scope(s):
//   kGTLAuthScopeZeppauserendpointUserinfoEmail
// Fetches a GTLZeppauserendpointZeppaUser.
+ (instancetype)queryForInsertZeppaUserWithObject:(GTLZeppauserendpointZeppaUser *)object;

// Method: zeppauserendpoint.listZeppaUser
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeZeppauserendpointUserinfoEmail
// Fetches a GTLZeppauserendpointCollectionResponseZeppaUser.
+ (instancetype)queryForListZeppaUser;

// Method: zeppauserendpoint.removeZeppaUser
//  Authorization scope(s):
//   kGTLAuthScopeZeppauserendpointUserinfoEmail
+ (instancetype)queryForRemoveZeppaUserWithIdentifier:(long long)identifier;

// Method: zeppauserendpoint.updateZeppaUser
//  Authorization scope(s):
//   kGTLAuthScopeZeppauserendpointUserinfoEmail
// Fetches a GTLZeppauserendpointZeppaUser.
+ (instancetype)queryForUpdateZeppaUserWithObject:(GTLZeppauserendpointZeppaUser *)object;

@end
