/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppauserinfoendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppauserinfoendpoint (5 custom class methods, 7 custom properties)

#import "GTLQueryZeppauserinfoendpoint.h"

#import "GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo.h"
#import "GTLZeppauserinfoendpointZeppaUserInfo.h"

@implementation GTLQueryZeppauserinfoendpoint

@dynamic cursor, fields, filter, identifier, limit, ordering, requestedParentId;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

#pragma mark - Service level methods
// These create a GTLQueryZeppauserinfoendpoint object.

+ (instancetype)queryForFetchZeppaUserInfoByParentIdWithRequestedParentId:(long long)requestedParentId {
  NSString *methodName = @"zeppauserinfoendpoint.fetchZeppaUserInfoByParentId";
  GTLQueryZeppauserinfoendpoint *query = [self queryWithMethodName:methodName];
  query.requestedParentId = requestedParentId;
  query.expectedObjectClass = [GTLZeppauserinfoendpointZeppaUserInfo class];
  return query;
}

+ (instancetype)queryForGetZeppaUserInfoWithIdentifier:(long long)identifier {
  NSString *methodName = @"zeppauserinfoendpoint.getZeppaUserInfo";
  GTLQueryZeppauserinfoendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLZeppauserinfoendpointZeppaUserInfo class];
  return query;
}

+ (instancetype)queryForInsertZeppaUserInfoWithObject:(GTLZeppauserinfoendpointZeppaUserInfo *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppauserinfoendpoint.insertZeppaUserInfo";
  GTLQueryZeppauserinfoendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppauserinfoendpointZeppaUserInfo class];
  return query;
}

+ (instancetype)queryForListZeppaUserInfo {
  NSString *methodName = @"zeppauserinfoendpoint.listZeppaUserInfo";
  GTLQueryZeppauserinfoendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo class];
  return query;
}

+ (instancetype)queryForUpdateZeppaUserInfoWithObject:(GTLZeppauserinfoendpointZeppaUserInfo *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppauserinfoendpoint.updateZeppaUserInfo";
  GTLQueryZeppauserinfoendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppauserinfoendpointZeppaUserInfo class];
  return query;
}

@end
