/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryEventtagfollowendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagfollowendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryEventtagfollowendpoint (5 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLEventtagfollowendpointEventTagFollow;

@interface GTLQueryEventtagfollowendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) NSInteger limit;
@property (nonatomic, copy) NSString *ordering;

#pragma mark - Service level methods
// These create a GTLQueryEventtagfollowendpoint object.

// Method: eventtagfollowendpoint.getEventTagFollow
//  Authorization scope(s):
//   kGTLAuthScopeEventtagfollowendpointUserinfoEmail
// Fetches a GTLEventtagfollowendpointEventTagFollow.
+ (instancetype)queryForGetEventTagFollowWithIdentifier:(long long)identifier;

// Method: eventtagfollowendpoint.insertEventTagFollow
//  Authorization scope(s):
//   kGTLAuthScopeEventtagfollowendpointUserinfoEmail
// Fetches a GTLEventtagfollowendpointEventTagFollow.
+ (instancetype)queryForInsertEventTagFollowWithObject:(GTLEventtagfollowendpointEventTagFollow *)object;

// Method: eventtagfollowendpoint.listEventTagFollow
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeEventtagfollowendpointUserinfoEmail
// Fetches a GTLEventtagfollowendpointCollectionResponseEventTagFollow.
+ (instancetype)queryForListEventTagFollow;

// Method: eventtagfollowendpoint.removeEventTagFollow
//  Authorization scope(s):
//   kGTLAuthScopeEventtagfollowendpointUserinfoEmail
+ (instancetype)queryForRemoveEventTagFollowWithIdentifier:(long long)identifier;

// Method: eventtagfollowendpoint.updateEventTagFollow
//  Authorization scope(s):
//   kGTLAuthScopeEventtagfollowendpointUserinfoEmail
// Fetches a GTLEventtagfollowendpointEventTagFollow.
+ (instancetype)queryForUpdateEventTagFollowWithObject:(GTLEventtagfollowendpointEventTagFollow *)object;

@end
