/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppausertouserrelationshipendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppausertouserrelationshipendpoint (5 custom class methods, 7 custom properties)

#import "GTLQueryZeppausertouserrelationshipendpoint.h"

#import "GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship.h"
#import "GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.h"

@implementation GTLQueryZeppausertouserrelationshipendpoint

@dynamic cursor, fields, filter, limit, ordering, relationshipId, userId;

#pragma mark - Service level methods
// These create a GTLQueryZeppausertouserrelationshipendpoint object.

+ (instancetype)queryForGetZeppaUserToUserRelationshipWithRelationshipId:(long long)relationshipId {
  NSString *methodName = @"zeppausertouserrelationshipendpoint.getZeppaUserToUserRelationship";
  GTLQueryZeppausertouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.relationshipId = relationshipId;
  query.expectedObjectClass = [GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship class];
  return query;
}

+ (instancetype)queryForInsertZeppaUserToUserRelationshipWithObject:(GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppausertouserrelationshipendpoint.insertZeppaUserToUserRelationship";
  GTLQueryZeppausertouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship class];
  return query;
}

+ (instancetype)queryForListZeppaUserToUserRelationship {
  NSString *methodName = @"zeppausertouserrelationshipendpoint.listZeppaUserToUserRelationship";
  GTLQueryZeppausertouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship class];
  return query;
}

+ (instancetype)queryForRemoveZeppaUserToUserRelationshipWithRelationshipId:(long long)relationshipId
                                                                     userId:(long long)userId {
  NSString *methodName = @"zeppausertouserrelationshipendpoint.removeZeppaUserToUserRelationship";
  GTLQueryZeppausertouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.relationshipId = relationshipId;
  query.userId = userId;
  return query;
}

+ (instancetype)queryForUpdateZeppaUserToUserRelationshipWithObject:(GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"zeppausertouserrelationshipendpoint.updateZeppaUserToUserRelationship";
  GTLQueryZeppausertouserrelationshipendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship class];
  return query;
}

@end
