/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryPhotoinfoendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   photoinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryPhotoinfoendpoint (4 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLPhotoinfoendpointPhotoInfo;

@interface GTLQueryPhotoinfoendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) NSInteger limit;

#pragma mark - Service level methods
// These create a GTLQueryPhotoinfoendpoint object.

// Method: photoinfoendpoint.getPhotoInfo
//  Authorization scope(s):
//   kGTLAuthScopePhotoinfoendpointUserinfoEmail
// Fetches a GTLPhotoinfoendpointPhotoInfo.
+ (instancetype)queryForGetPhotoInfoWithIdentifier:(long long)identifier;

// Method: photoinfoendpoint.insertPhotoInfo
//  Authorization scope(s):
//   kGTLAuthScopePhotoinfoendpointUserinfoEmail
// Fetches a GTLPhotoinfoendpointPhotoInfo.
+ (instancetype)queryForInsertPhotoInfoWithObject:(GTLPhotoinfoendpointPhotoInfo *)object;

// Method: photoinfoendpoint.listPhotoInfo
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopePhotoinfoendpointUserinfoEmail
// Fetches a GTLPhotoinfoendpointCollectionResponsePhotoInfo.
+ (instancetype)queryForListPhotoInfo;

// Method: photoinfoendpoint.removePhotoInfo
//  Authorization scope(s):
//   kGTLAuthScopePhotoinfoendpointUserinfoEmail
+ (instancetype)queryForRemovePhotoInfoWithIdentifier:(long long)identifier;

@end
