/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppausertouserrelationshipendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppausertouserrelationshipendpoint (5 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship;

@interface GTLQueryZeppausertouserrelationshipendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, copy) NSString *filter;
@property (nonatomic, assign) NSInteger limit;
@property (nonatomic, copy) NSString *ordering;
@property (nonatomic, assign) long long relationshipId;
@property (nonatomic, assign) long long userId;

#pragma mark - Service level methods
// These create a GTLQueryZeppausertouserrelationshipendpoint object.

// Method: zeppausertouserrelationshipendpoint.getZeppaUserToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppausertouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.
+ (instancetype)queryForGetZeppaUserToUserRelationshipWithRelationshipId:(long long)relationshipId;

// Method: zeppausertouserrelationshipendpoint.insertZeppaUserToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppausertouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.
+ (instancetype)queryForInsertZeppaUserToUserRelationshipWithObject:(GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship *)object;

// Method: zeppausertouserrelationshipendpoint.listZeppaUserToUserRelationship
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeZeppausertouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship.
+ (instancetype)queryForListZeppaUserToUserRelationship;

// Method: zeppausertouserrelationshipendpoint.removeZeppaUserToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppausertouserrelationshipendpointUserinfoEmail
+ (instancetype)queryForRemoveZeppaUserToUserRelationshipWithRelationshipId:(long long)relationshipId
                                                                     userId:(long long)userId;

// Method: zeppausertouserrelationshipendpoint.updateZeppaUserToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppausertouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.
+ (instancetype)queryForUpdateZeppaUserToUserRelationshipWithObject:(GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship *)object;

@end
