/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppanotificationendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppanotificationendpoint (5 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLZeppanotificationendpointZeppaNotification;

@interface GTLQueryZeppanotificationendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) NSInteger limit;
@property (nonatomic, copy) NSString *ordering;

#pragma mark - Service level methods
// These create a GTLQueryZeppanotificationendpoint object.

// Method: zeppanotificationendpoint.getZeppaNotification
//  Authorization scope(s):
//   kGTLAuthScopeZeppanotificationendpointUserinfoEmail
// Fetches a GTLZeppanotificationendpointZeppaNotification.
+ (instancetype)queryForGetZeppaNotificationWithIdentifier:(long long)identifier;

// Method: zeppanotificationendpoint.insertZeppaNotification
//  Authorization scope(s):
//   kGTLAuthScopeZeppanotificationendpointUserinfoEmail
// Fetches a GTLZeppanotificationendpointZeppaNotification.
+ (instancetype)queryForInsertZeppaNotificationWithObject:(GTLZeppanotificationendpointZeppaNotification *)object;

// Method: zeppanotificationendpoint.listZeppaNotification
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeZeppanotificationendpointUserinfoEmail
// Fetches a GTLZeppanotificationendpointCollectionResponseZeppaNotification.
+ (instancetype)queryForListZeppaNotification;

// Method: zeppanotificationendpoint.removeZeppaNotification
//  Authorization scope(s):
//   kGTLAuthScopeZeppanotificationendpointUserinfoEmail
+ (instancetype)queryForRemoveZeppaNotificationWithIdentifier:(long long)identifier;

// Method: zeppanotificationendpoint.updateZeppaNotification
//  Authorization scope(s):
//   kGTLAuthScopeZeppanotificationendpointUserinfoEmail
// Fetches a GTLZeppanotificationendpointZeppaNotification.
+ (instancetype)queryForUpdateZeppaNotificationWithObject:(GTLZeppanotificationendpointZeppaNotification *)object;

@end
