/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryEventtagendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   eventtagendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryEventtagendpoint (4 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLEventtagendpointEventTag;

@interface GTLQueryEventtagendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) NSInteger limit;
@property (nonatomic, copy) NSString *ordering;
@property (nonatomic, assign) long long tagId;

#pragma mark - Service level methods
// These create a GTLQueryEventtagendpoint object.

// Method: eventtagendpoint.getEventTag
//  Authorization scope(s):
//   kGTLAuthScopeEventtagendpointUserinfoEmail
// Fetches a GTLEventtagendpointEventTag.
+ (instancetype)queryForGetEventTagWithIdentifier:(long long)identifier;

// Method: eventtagendpoint.insertEventTag
//  Authorization scope(s):
//   kGTLAuthScopeEventtagendpointUserinfoEmail
// Fetches a GTLEventtagendpointEventTag.
+ (instancetype)queryForInsertEventTagWithObject:(GTLEventtagendpointEventTag *)object;

// Method: eventtagendpoint.listEventTag
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeEventtagendpointUserinfoEmail
// Fetches a GTLEventtagendpointCollectionResponseEventTag.
+ (instancetype)queryForListEventTag;

// Method: eventtagendpoint.removeEventTag
//  Authorization scope(s):
//   kGTLAuthScopeEventtagendpointUserinfoEmail
+ (instancetype)queryForRemoveEventTagWithTagId:(long long)tagId;

@end
