/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppaeventtouserrelationshipendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppaeventtouserrelationshipendpoint (5 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship;

@interface GTLQueryZeppaeventtouserrelationshipendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) NSInteger limit;
@property (nonatomic, copy) NSString *ordering;

#pragma mark - Service level methods
// These create a GTLQueryZeppaeventtouserrelationshipendpoint object.

// Method: zeppaeventtouserrelationshipendpoint.getZeppaEventToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventtouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.
+ (instancetype)queryForGetZeppaEventToUserRelationshipWithIdentifier:(long long)identifier;

// Method: zeppaeventtouserrelationshipendpoint.insertZeppaEventToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventtouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.
+ (instancetype)queryForInsertZeppaEventToUserRelationshipWithObject:(GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship *)object;

// Method: zeppaeventtouserrelationshipendpoint.listZeppaEventToUserRelationship
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventtouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship.
+ (instancetype)queryForListZeppaEventToUserRelationship;

// Method: zeppaeventtouserrelationshipendpoint.removeZeppaEventToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventtouserrelationshipendpointUserinfoEmail
+ (instancetype)queryForRemoveZeppaEventToUserRelationshipWithIdentifier:(long long)identifier;

// Method: zeppaeventtouserrelationshipendpoint.updateZeppaEventToUserRelationship
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventtouserrelationshipendpointUserinfoEmail
// Fetches a GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.
+ (instancetype)queryForUpdateZeppaEventToUserRelationshipWithObject:(GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship *)object;

@end
