/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryZeppaeventendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryZeppaeventendpoint (5 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLZeppaeventendpointZeppaEvent;

@interface GTLQueryZeppaeventendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *cursor;
@property (nonatomic, copy) NSString *filter;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) NSInteger limit;
@property (nonatomic, copy) NSString *ordering;

#pragma mark - Service level methods
// These create a GTLQueryZeppaeventendpoint object.

// Method: zeppaeventendpoint.getZeppaEvent
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventendpointUserinfoEmail
// Fetches a GTLZeppaeventendpointZeppaEvent.
+ (instancetype)queryForGetZeppaEventWithIdentifier:(long long)identifier;

// Method: zeppaeventendpoint.insertZeppaEvent
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventendpointUserinfoEmail
// Fetches a GTLZeppaeventendpointZeppaEvent.
+ (instancetype)queryForInsertZeppaEventWithObject:(GTLZeppaeventendpointZeppaEvent *)object;

// Method: zeppaeventendpoint.listZeppaEvent
//  Optional:
//   cursor: NSString
//   filter: NSString
//   limit: NSInteger
//   ordering: NSString
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventendpointUserinfoEmail
// Fetches a GTLZeppaeventendpointCollectionResponseZeppaEvent.
+ (instancetype)queryForListZeppaEvent;

// Method: zeppaeventendpoint.removeZeppaEvent
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventendpointUserinfoEmail
+ (instancetype)queryForRemoveZeppaEventWithIdentifier:(long long)identifier;

// Method: zeppaeventendpoint.updateZeppaEvent
//  Authorization scope(s):
//   kGTLAuthScopeZeppaeventendpointUserinfoEmail
// Fetches a GTLZeppaeventendpointZeppaEvent.
+ (instancetype)queryForUpdateZeppaEventWithObject:(GTLZeppaeventendpointZeppaEvent *)object;

@end
