/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLServiceZeppaclientapi.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceZeppaclientapi (0 custom class methods, 0 custom properties)

#import "GTLZeppaclientapi.h"

@implementation GTLServiceZeppaclientapi

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQueryZeppaclientapi class],
    [GTLZeppaclientapiClientInfo class],
    [GTLZeppaclientapiCollectionResponseDeviceInfo class],
    [GTLZeppaclientapiCollectionResponseEventComment class],
    [GTLZeppaclientapiCollectionResponseEventTag class],
    [GTLZeppaclientapiCollectionResponseEventTagFollow class],
    [GTLZeppaclientapiCollectionResponseInviteGroup class],
    [GTLZeppaclientapiCollectionResponsePhotoInfo class],
    [GTLZeppaclientapiCollectionResponseZeppaEvent class],
    [GTLZeppaclientapiCollectionResponseZeppaEventToUserRelationship class],
    [GTLZeppaclientapiCollectionResponseZeppaNotification class],
    [GTLZeppaclientapiCollectionResponseZeppaUserInfo class],
    [GTLZeppaclientapiCollectionResponseZeppaUserToUserRelationship class],
    [GTLZeppaclientapiDeviceInfo class],
    [GTLZeppaclientapiEventComment class],
    [GTLZeppaclientapiEventTag class],
    [GTLZeppaclientapiEventTagFollow class],
    [GTLZeppaclientapiInviteGroup class],
    [GTLZeppaclientapiKey class],
    [GTLZeppaclientapiPhotoInfo class],
    [GTLZeppaclientapiZeppaEvent class],
    [GTLZeppaclientapiZeppaEventToUserRelationship class],
    [GTLZeppaclientapiZeppaFeedback class],
    [GTLZeppaclientapiZeppaNotification class],
    [GTLZeppaclientapiZeppaUser class],
    [GTLZeppaclientapiZeppaUserInfo class],
    [GTLZeppaclientapiZeppaUserToUserRelationship class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://zeppa-cloud-1821.appspot.com/_ah/spi/rpc?prettyPrint=false"];
      self.APIKey = kZeppaGooglePlusClientIdKey;
//      self.rpcURL = [NSURL URLWithString:@"https://zeppa-cloud-1821.appspot.com/_ah/spi/"];
      
  }
  return self;
}

@end
