/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaNotification.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaNotification (0 custom class methods, 13 custom properties)

#import "GTLZeppaclientapiZeppaNotification.h"

#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaNotification
//

@implementation GTLZeppaclientapiZeppaNotification
@dynamic created, eventId, expires, extraMessage, hasSeen, identifier, key,
         recipient, recipientId, sender, senderId, type, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
