/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventendpoint/v1
// Description:
//   This is an API

#import "GTLZeppaeventendpointConstants.h"

#import "GTLZeppaeventendpointCollectionResponseZeppaEvent.h"
#import "GTLZeppaeventendpointKey.h"
#import "GTLZeppaeventendpointZeppaEvent.h"

#import "GTLQueryZeppaeventendpoint.h"
#import "GTLServiceZeppaeventendpoint.h"
