/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiInviteGroup.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiInviteGroup (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppaclientapiKey;

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiInviteGroup
//

@interface GTLZeppaclientapiInviteGroup : GTLObject
@property (nonatomic, retain) NSArray *emails;  // of NSString
@property (nonatomic, retain) NSArray *groupMemberKeys;  // of GTLZeppaclientapiKey
@property (nonatomic, retain) NSArray *suggestedTags;  // of NSString
@end
