/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppafeedbackendpointCollectionResponseZeppaFeedback.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppafeedbackendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppafeedbackendpointCollectionResponseZeppaFeedback (0 custom class methods, 2 custom properties)

#import "GTLZeppafeedbackendpointCollectionResponseZeppaFeedback.h"

#import "GTLZeppafeedbackendpointZeppaFeedback.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppafeedbackendpointCollectionResponseZeppaFeedback
//

@implementation GTLZeppafeedbackendpointCollectionResponseZeppaFeedback
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppafeedbackendpointZeppaFeedback class]
  };
  return map;
}

@end
