/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship (0 custom class methods, 7 custom properties)

#import "GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.h"

#import "GTLZeppausertouserrelationshipendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship
//

@implementation GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship
@dynamic created, creatorId, identifier, key, relationshipType, subjectId,
         updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
