/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppanotificationendpointKey.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppanotificationendpointKey (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppanotificationendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLZeppanotificationendpointKey
//

@interface GTLZeppanotificationendpointKey : GTLObject
@property (nonatomic, copy) NSString *appId;
@property (nonatomic, retain) NSNumber *complete;  // boolValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, copy) NSString *kind;
@property (nonatomic, copy) NSString *name;

// Remapped to 'namespaceProperty' to avoid language reserved word 'namespace'.
@property (nonatomic, copy) NSString *namespaceProperty;

@property (nonatomic, retain) GTLZeppanotificationendpointKey *parent;
@end
