/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaFeedback.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaFeedback (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppaclientapiKey;

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaFeedback
//

@interface GTLZeppaclientapiZeppaFeedback : GTLObject
@property (nonatomic, retain) NSNumber *created;  // longLongValue
@property (nonatomic, copy) NSString *deviceType;
@property (nonatomic, copy) NSString *feedback;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLZeppaclientapiKey *key;
@property (nonatomic, retain) NSNumber *rating;  // doubleValue
@property (nonatomic, copy) NSString *releaseCode;
@property (nonatomic, copy) NSString *subject;
@property (nonatomic, retain) NSNumber *updated;  // longLongValue
@property (nonatomic, retain) NSNumber *userId;  // longLongValue
@end
