/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship (0 custom class methods, 13 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppaeventtouserrelationshipendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship
//

@interface GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship : GTLObject
@property (nonatomic, retain) NSNumber *created;  // longLongValue
@property (nonatomic, retain) NSNumber *eventHostId;  // longLongValue
@property (nonatomic, retain) NSNumber *eventId;  // longLongValue
@property (nonatomic, retain) NSNumber *expires;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) NSNumber *invitedByUserId;  // longLongValue
@property (nonatomic, retain) NSNumber *isAttending;  // boolValue
@property (nonatomic, retain) NSNumber *isRecommended;  // boolValue
@property (nonatomic, retain) NSNumber *isWatching;  // boolValue
@property (nonatomic, retain) GTLZeppaeventtouserrelationshipendpointKey *key;
@property (nonatomic, retain) NSNumber *updated;  // longLongValue
@property (nonatomic, retain) NSNumber *userId;  // longLongValue
@property (nonatomic, retain) NSNumber *wasInvited;  // boolValue
@end
