/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiInviteGroup.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiInviteGroup (0 custom class methods, 3 custom properties)

#import "GTLZeppaclientapiInviteGroup.h"

#import "GTLZeppaclientapiKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiInviteGroup
//

@implementation GTLZeppaclientapiInviteGroup
@dynamic emails, groupMemberKeys, suggestedTags;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"emails" : [NSString class],
    @"groupMemberKeys" : [GTLZeppaclientapiKey class],
    @"suggestedTags" : [NSString class]
  };
  return map;
}

@end
