/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaEvent.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaEvent (0 custom class methods, 21 custom properties)

#import "GTLZeppaclientapiZeppaEvent.h"

#import "GTLZeppaclientapiEventComment.h"
#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiZeppaEventToUserRelationship.h"
#import "GTLZeppaclientapiZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaEvent
//

@implementation GTLZeppaclientapiZeppaEvent
@dynamic attendeeRelationships, comments, created, descriptionProperty,
         displayLocation, end, googleCalendarEventId, googleCalendarId,
         guestsMayInvite, host, hostId, iCalUID, identifier, invitedUserIds,
         key, mapsLocation, privacy, start, tagIds, title, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"descriptionProperty" : @"description",
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"attendeeRelationships" : [GTLZeppaclientapiZeppaEventToUserRelationship class],
    @"comments" : [GTLZeppaclientapiEventComment class],
    @"invitedUserIds" : [NSNumber class],
    @"tagIds" : [NSNumber class]
  };
  return map;
}

@end
