/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaUserToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaUserToUserRelationship (0 custom class methods, 8 custom properties)

#import "GTLZeppaclientapiZeppaUserToUserRelationship.h"

#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiZeppaUserInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaUserToUserRelationship
//

@implementation GTLZeppaclientapiZeppaUserToUserRelationship
@dynamic created, creatorId, identifier, key, relationshipType, subjectId,
         updated, userInfo;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
