/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventendpoint/v1
// Description:
//   This is an API

#import "GTLZeppaeventendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppaeventendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLZeppaeventendpoint - EventPrivacyType
NSString * const kGTLZeppaeventendpoint_EventPrivacyType_Casual = @"CASUAL";
NSString * const kGTLZeppaeventendpoint_EventPrivacyType_Private = @"PRIVATE";
