/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseEventComment.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseEventComment (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseEventComment.h"

#import "GTLZeppaclientapiEventComment.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseEventComment
//

@implementation GTLZeppaclientapiCollectionResponseEventComment
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiEventComment class]
  };
  return map;
}

@end
