/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopeZeppaclientapiUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"

// GTLQueryZeppaclientapi - DeviceType
GTL_EXTERN NSString * const kGTLZeppaclientapiDeviceTypeAndroid;  // "ANDROID"
GTL_EXTERN NSString * const kGTLZeppaclientapiDeviceTypeIOS;    // "iOS"

// GTLZeppaclientapi - DeviceType
GTL_EXTERN NSString * const kGTLZeppaclientapi_DeviceType_Android;  // "ANDROID"
GTL_EXTERN NSString * const kGTLZeppaclientapi_DeviceType_IOS;  // "iOS"

// GTLZeppaclientapi - EventPrivacyType
GTL_EXTERN NSString * const kGTLZeppaclientapi_EventPrivacyType_Casual;  // "CASUAL"
GTL_EXTERN NSString * const kGTLZeppaclientapi_EventPrivacyType_Private;  // "PRIVATE"

// GTLZeppaclientapi - NotificationType
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_CommentOnPost;  // "COMMENT_ON_POST"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_DirectInvite;  // "DIRECT_INVITE"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_EventCanceled;  // "EVENT_CANCELED"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_EventRecommendation;  // "EVENT_RECOMMENDATION"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_EventUpdated;  // "EVENT_UPDATED"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_MingleAccepted;  // "MINGLE_ACCEPTED"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_MingleRequest;  // "MINGLE_REQUEST"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_UserJoined;  // "USER_JOINED"
GTL_EXTERN NSString * const kGTLZeppaclientapi_NotificationType_UserLeaving;  // "USER_LEAVING"

// GTLZeppaclientapi - UserRelationshipType
GTL_EXTERN NSString * const kGTLZeppaclientapi_UserRelationshipType_Mingling;  // "MINGLING"
GTL_EXTERN NSString * const kGTLZeppaclientapi_UserRelationshipType_PendingRequest;  // "PENDING_REQUEST"
