/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseZeppaUserToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseZeppaUserToUserRelationship (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseZeppaUserToUserRelationship.h"

#import "GTLZeppaclientapiZeppaUserToUserRelationship.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseZeppaUserToUserRelationship
//

@implementation GTLZeppaclientapiCollectionResponseZeppaUserToUserRelationship
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiZeppaUserToUserRelationship class]
  };
  return map;
}

@end
