/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaEvent.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaEvent (0 custom class methods, 21 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppaclientapiKey;
@class GTLZeppaclientapiZeppaUser;

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaEvent
//

@interface GTLZeppaclientapiZeppaEvent : GTLObject
@property (nonatomic, retain) NSNumber *created;  // longLongValue

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (nonatomic, copy) NSString *descriptionProperty;

@property (nonatomic, copy) NSString *displayLocation;
@property (nonatomic, retain) NSNumber *end;  // longLongValue
@property (nonatomic, copy) NSString *googleCalendarEventId;
@property (nonatomic, copy) NSString *googleCalendarId;
@property (nonatomic, retain) NSNumber *guestsMayInvite;  // boolValue
@property (nonatomic, retain) GTLZeppaclientapiZeppaUser *host;
@property (nonatomic, retain) NSNumber *hostId;  // longLongValue
@property (nonatomic, copy) NSString *iCalUID;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) NSArray *invitedUserIds;  // of NSNumber (longLongValue)
@property (nonatomic, retain) GTLZeppaclientapiKey *key;
@property (nonatomic, retain) NSNumber *latitude;  // floatValue
@property (nonatomic, retain) NSNumber *longitude;  // floatValue
@property (nonatomic, copy) NSString *mapsLocation;
@property (nonatomic, copy) NSString *privacy;
@property (nonatomic, retain) NSNumber *start;  // longLongValue
@property (nonatomic, retain) NSArray *tagIds;  // of NSNumber (longLongValue)
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) NSNumber *updated;  // longLongValue
@end
