/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiPhotoInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiPhotoInfo (0 custom class methods, 5 custom properties)

#import "GTLZeppaclientapiPhotoInfo.h"

#import "GTLZeppaclientapiKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiPhotoInfo
//

@implementation GTLZeppaclientapiPhotoInfo
@dynamic blobKey, identifier, key, ownerEmail, url;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
