/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventendpointConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventendpoint/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// Authorization scope
// View your email address
GTL_EXTERN NSString * const kGTLAuthScopeZeppaeventendpointUserinfoEmail;  // "https://www.googleapis.com/auth/userinfo.email"

// GTLZeppaeventendpoint - EventPrivacyType
GTL_EXTERN NSString * const kGTLZeppaeventendpoint_EventPrivacyType_Casual;  // "CASUAL"
GTL_EXTERN NSString * const kGTLZeppaeventendpoint_EventPrivacyType_Private;  // "PRIVATE"
