/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserinfoendpointKey.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppauserinfoendpointKey (0 custom class methods, 7 custom properties)

#import "GTLZeppauserinfoendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppauserinfoendpointKey
//

@implementation GTLZeppauserinfoendpointKey
@dynamic appId, complete, identifier, kind, name, namespaceProperty, parent;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id",
    @"namespaceProperty" : @"namespace"
  };
  return map;
}

@end
