/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiClientInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiClientInfo (0 custom class methods, 7 custom properties)

#import "GTLZeppaclientapiClientInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiClientInfo
//

@implementation GTLZeppaclientapiClientInfo
@dynamic currentBugfix, currentUpdate, currentVersion, message, minBugfix,
         minUpdate, minVersion;
@end
