/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaUserToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaUserToUserRelationship (0 custom class methods, 10 custom properties)

#import "GTLZeppaclientapiZeppaUserToUserRelationship.h"

#import "GTLZeppaclientapiEventTagFollow.h"
#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaUserToUserRelationship
//

@implementation GTLZeppaclientapiZeppaUserToUserRelationship
@dynamic created, creator, creatorId, identifier, key, relationshipType,
         subject, subjectId, tagFollows, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"tagFollows" : [GTLZeppaclientapiEventTagFollow class]
  };
  return map;
}

@end
