/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppausertouserrelationshipendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API

#import "GTLZeppausertouserrelationshipendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppausertouserrelationshipendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLZeppausertouserrelationshipendpoint - UserRelationshipType
NSString * const kGTLZeppausertouserrelationshipendpoint_UserRelationshipType_Mingling = @"MINGLING";
NSString * const kGTLZeppausertouserrelationshipendpoint_UserRelationshipType_PendingRequest = @"PENDING_REQUEST";
