/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship (0 custom class methods, 2 custom properties)

#import "GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship.h"

#import "GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship
//

@implementation GTLZeppausertouserrelationshipendpointCollectionResponseZeppaUserToUserRelationship
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppausertouserrelationshipendpointZeppaUserToUserRelationship class]
  };
  return map;
}

@end
