/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseZeppaUserInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseZeppaUserInfo (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseZeppaUserInfo.h"

#import "GTLZeppaclientapiZeppaUserInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseZeppaUserInfo
//

@implementation GTLZeppaclientapiCollectionResponseZeppaUserInfo
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiZeppaUserInfo class]
  };
  return map;
}

@end
