/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserendpointZeppaUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppauserendpointZeppaUser (0 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppauserendpointKey;
@class GTLZeppauserendpointZeppaUserInfo;

// ----------------------------------------------------------------------------
//
//   GTLZeppauserendpointZeppaUser
//

@interface GTLZeppauserendpointZeppaUser : GTLObject
@property (nonatomic, copy) NSString *authEmail;
@property (nonatomic, retain) NSNumber *created;  // longLongValue
@property (nonatomic, copy) NSString *googleProfileId;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLZeppauserendpointKey *key;
@property (nonatomic, retain) NSNumber *updated;  // longLongValue
@property (nonatomic, retain) GTLZeppauserendpointZeppaUserInfo *userInfo;
@property (nonatomic, copy) NSString *zeppaCalendarId;
@end
