/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaUserToUserRelationship.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaUserToUserRelationship (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppaclientapiEventTagFollow;
@class GTLZeppaclientapiKey;
@class GTLZeppaclientapiZeppaUser;

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaUserToUserRelationship
//

@interface GTLZeppaclientapiZeppaUserToUserRelationship : GTLObject
@property (nonatomic, retain) NSNumber *created;  // longLongValue
@property (nonatomic, retain) GTLZeppaclientapiZeppaUser *creator;
@property (nonatomic, retain) NSNumber *creatorId;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLZeppaclientapiKey *key;
@property (nonatomic, copy) NSString *relationshipType;
@property (nonatomic, retain) GTLZeppaclientapiZeppaUser *subject;
@property (nonatomic, retain) NSNumber *subjectId;  // longLongValue
@property (nonatomic, retain) NSArray *tagFollows;  // of GTLZeppaclientapiEventTagFollow
@property (nonatomic, retain) NSNumber *updated;  // longLongValue
@end
