/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API

#import "GTLZeppaclientapiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppaclientapiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// GTLQueryZeppaclientapi - DeviceType
NSString * const kGTLZeppaclientapiDeviceTypeAndroid = @"ANDROID";
NSString * const kGTLZeppaclientapiDeviceTypeIOS     = @"iOS";

// GTLZeppaclientapi - DeviceType
NSString * const kGTLZeppaclientapi_DeviceType_Android = @"ANDROID";
NSString * const kGTLZeppaclientapi_DeviceType_IOS     = @"iOS";

// GTLZeppaclientapi - EventPrivacyType
NSString * const kGTLZeppaclientapi_EventPrivacyType_Casual  = @"CASUAL";
NSString * const kGTLZeppaclientapi_EventPrivacyType_Private = @"PRIVATE";

// GTLZeppaclientapi - NotificationType
NSString * const kGTLZeppaclientapi_NotificationType_CommentOnPost = @"COMMENT_ON_POST";
NSString * const kGTLZeppaclientapi_NotificationType_DirectInvite = @"DIRECT_INVITE";
NSString * const kGTLZeppaclientapi_NotificationType_EventCanceled = @"EVENT_CANCELED";
NSString * const kGTLZeppaclientapi_NotificationType_EventRecommendation = @"EVENT_RECOMMENDATION";
NSString * const kGTLZeppaclientapi_NotificationType_EventUpdated = @"EVENT_UPDATED";
NSString * const kGTLZeppaclientapi_NotificationType_MingleAccepted = @"MINGLE_ACCEPTED";
NSString * const kGTLZeppaclientapi_NotificationType_MingleRequest = @"MINGLE_REQUEST";
NSString * const kGTLZeppaclientapi_NotificationType_UserJoined = @"USER_JOINED";
NSString * const kGTLZeppaclientapi_NotificationType_UserLeaving = @"USER_LEAVING";

// GTLZeppaclientapi - UserRelationshipType
NSString * const kGTLZeppaclientapi_UserRelationshipType_Mingling = @"MINGLING";
NSString * const kGTLZeppaclientapi_UserRelationshipType_PendingRequest = @"PENDING_REQUEST";
