/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppafeedbackendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppafeedbackendpoint/v1
// Description:
//   This is an API

#import "GTLZeppafeedbackendpointConstants.h"

#import "GTLZeppafeedbackendpointCollectionResponseZeppaFeedback.h"
#import "GTLZeppafeedbackendpointKey.h"
#import "GTLZeppafeedbackendpointZeppaFeedback.h"

#import "GTLQueryZeppafeedbackendpoint.h"
#import "GTLServiceZeppafeedbackendpoint.h"
