/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiKey.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiKey (0 custom class methods, 7 custom properties)

#import "GTLZeppaclientapiKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiKey
//

@implementation GTLZeppaclientapiKey
@dynamic appId, complete, identifier, kind, name, namespaceProperty, parent;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id",
    @"namespaceProperty" : @"namespace"
  };
  return map;
}

@end
