/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiEventTagFollow.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiEventTagFollow (0 custom class methods, 9 custom properties)

#import "GTLZeppaclientapiEventTagFollow.h"

#import "GTLZeppaclientapiEventTag.h"
#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiEventTagFollow
//

@implementation GTLZeppaclientapiEventTagFollow
@dynamic created, follower, followerId, identifier, key, tag, tagId, tagOwnerId,
         updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
