/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship (0 custom class methods, 13 custom properties)

#import "GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.h"

#import "GTLZeppaeventtouserrelationshipendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship
//

@implementation GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship
@dynamic created, eventHostId, eventId, expires, identifier, invitedByUserId,
         isAttending, isRecommended, isWatching, key, updated, userId,
         wasInvited;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
