/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaeventtouserrelationshipendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaeventtouserrelationshipendpoint/v1
// Description:
//   This is an API

#import "GTLZeppaeventtouserrelationshipendpointConstants.h"

#import "GTLZeppaeventtouserrelationshipendpointCollectionResponseZeppaEventToUserRelationship.h"
#import "GTLZeppaeventtouserrelationshipendpointKey.h"
#import "GTLZeppaeventtouserrelationshipendpointZeppaEventToUserRelationship.h"

#import "GTLQueryZeppaeventtouserrelationshipendpoint.h"
#import "GTLServiceZeppaeventtouserrelationshipendpoint.h"
