/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseEventTagFollow.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseEventTagFollow (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseEventTagFollow.h"

#import "GTLZeppaclientapiEventTagFollow.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseEventTagFollow
//

@implementation GTLZeppaclientapiCollectionResponseEventTagFollow
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiEventTagFollow class]
  };
  return map;
}

@end
