/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserendpointZeppaUserInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppauserendpointZeppaUserInfo (0 custom class methods, 9 custom properties)

#import "GTLZeppauserendpointZeppaUserInfo.h"

#import "GTLZeppauserendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppauserendpointZeppaUserInfo
//

@implementation GTLZeppauserendpointZeppaUserInfo
@dynamic created, familyName, givenName, googleAccountEmail, identifier,
         imageUrl, key, primaryUnformattedNumber, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
