/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserinfoendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserinfoendpoint/v1
// Description:
//   This is an API

#import "GTLZeppauserinfoendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeZeppauserinfoendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
