/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppanotificationendpointZeppaNotification.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppanotificationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppanotificationendpointZeppaNotification (0 custom class methods, 12 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppanotificationendpointKey;

// ----------------------------------------------------------------------------
//
//   GTLZeppanotificationendpointZeppaNotification
//

@interface GTLZeppanotificationendpointZeppaNotification : GTLObject
@property (nonatomic, retain) NSNumber *created;  // longLongValue
@property (nonatomic, retain) NSNumber *eventId;  // longLongValue
@property (nonatomic, retain) NSNumber *expires;  // longLongValue
@property (nonatomic, copy) NSString *extraMessage;
@property (nonatomic, retain) NSNumber *hasSeen;  // boolValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLZeppanotificationendpointKey *key;
@property (nonatomic, retain) NSNumber *recipientId;  // longLongValue
@property (nonatomic, retain) NSNumber *senderId;  // longLongValue
@property (nonatomic, copy) NSString *type;
@property (nonatomic, retain) NSNumber *updated;  // longLongValue
@property (nonatomic, retain) NSNumber *userId;  // longLongValue
@end
