/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiEventTag.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiEventTag (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLZeppaclientapiKey;
@class GTLZeppaclientapiZeppaUser;

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiEventTag
//

@interface GTLZeppaclientapiEventTag : GTLObject
@property (nonatomic, retain) NSNumber *created;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLZeppaclientapiKey *key;
@property (nonatomic, retain) GTLZeppaclientapiZeppaUser *owner;
@property (nonatomic, retain) NSNumber *ownerId;  // longLongValue
@property (nonatomic, copy) NSString *tagText;
@property (nonatomic, retain) NSNumber *updated;  // longLongValue
@end
