/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiDeviceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiDeviceInfo (0 custom class methods, 13 custom properties)

#import "GTLZeppaclientapiDeviceInfo.h"

#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiDeviceInfo
//

@implementation GTLZeppaclientapiDeviceInfo
@dynamic bugfix, created, identifier, key, lastLogin, loggedIn, owner, ownerId,
         phoneType, registrationId, update, updated, version;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
