/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiInviteGroup.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiInviteGroup (0 custom class methods, 1 custom properties)

#import "GTLZeppaclientapiInviteGroup.h"

#import "GTLZeppaclientapiZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiInviteGroup
//

@implementation GTLZeppaclientapiInviteGroup
@dynamic groupMembers;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"groupMembers" : [GTLZeppaclientapiZeppaUser class]
  };
  return map;
}

@end
