/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseEventTag.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseEventTag (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseEventTag.h"

#import "GTLZeppaclientapiEventTag.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseEventTag
//

@implementation GTLZeppaclientapiCollectionResponseEventTag
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiEventTag class]
  };
  return map;
}

@end
