/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiEventComment.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiEventComment (0 custom class methods, 9 custom properties)

#import "GTLZeppaclientapiEventComment.h"

#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiZeppaEvent.h"
#import "GTLZeppaclientapiZeppaUser.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiEventComment
//

@implementation GTLZeppaclientapiEventComment
@dynamic commenter, commenterId, created, event, eventId, identifier, key, text,
         updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
