/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponsePhotoInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponsePhotoInfo (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponsePhotoInfo.h"

#import "GTLZeppaclientapiPhotoInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponsePhotoInfo
//

@implementation GTLZeppaclientapiCollectionResponsePhotoInfo
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiPhotoInfo class]
  };
  return map;
}

@end
