/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiClientInfo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiClientInfo (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiClientInfo
//

@interface GTLZeppaclientapiClientInfo : GTLObject
@property (nonatomic, retain) NSNumber *currentBugfix;  // intValue
@property (nonatomic, retain) NSNumber *currentUpdate;  // intValue
@property (nonatomic, retain) NSNumber *currentVersion;  // intValue
@property (nonatomic, copy) NSString *message;
@property (nonatomic, retain) NSNumber *minBugfix;  // intValue
@property (nonatomic, retain) NSNumber *minUpdate;  // intValue
@property (nonatomic, retain) NSNumber *minVersion;  // intValue
@end
