/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiZeppaEventToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiZeppaEventToUserRelationship (0 custom class methods, 13 custom properties)

#import "GTLZeppaclientapiZeppaEventToUserRelationship.h"

#import "GTLZeppaclientapiKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiZeppaEventToUserRelationship
//

@implementation GTLZeppaclientapiZeppaEventToUserRelationship
@dynamic created, eventHostId, eventId, expires, identifier, invitedByUserId,
         isAttending, isRecommended, isWatching, key, updated, userId,
         wasInvited;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
