/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseZeppaNotification.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseZeppaNotification (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseZeppaNotification.h"

#import "GTLZeppaclientapiZeppaNotification.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseZeppaNotification
//

@implementation GTLZeppaclientapiCollectionResponseZeppaNotification
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiZeppaNotification class]
  };
  return map;
}

@end
