/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppausertouserrelationshipendpointKey.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppausertouserrelationshipendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppausertouserrelationshipendpointKey (0 custom class methods, 7 custom properties)

#import "GTLZeppausertouserrelationshipendpointKey.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppausertouserrelationshipendpointKey
//

@implementation GTLZeppausertouserrelationshipendpointKey
@dynamic appId, complete, identifier, kind, name, namespaceProperty, parent;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id",
    @"namespaceProperty" : @"namespace"
  };
  return map;
}

@end
