/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppauserinfoendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo (0 custom class methods, 2 custom properties)

#import "GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo.h"

#import "GTLZeppauserinfoendpointZeppaUserInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo
//

@implementation GTLZeppauserinfoendpointCollectionResponseZeppaUserInfo
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppauserinfoendpointZeppaUserInfo class]
  };
  return map;
}

@end
