/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API

#import "GTLZeppaclientapiConstants.h"

#import "GTLZeppaclientapiClientInfo.h"
#import "GTLZeppaclientapiCollectionResponseDeviceInfo.h"
#import "GTLZeppaclientapiCollectionResponseEventComment.h"
#import "GTLZeppaclientapiCollectionResponseEventTag.h"
#import "GTLZeppaclientapiCollectionResponseEventTagFollow.h"
#import "GTLZeppaclientapiCollectionResponseInviteGroup.h"
#import "GTLZeppaclientapiCollectionResponsePhotoInfo.h"
#import "GTLZeppaclientapiCollectionResponseZeppaEvent.h"
#import "GTLZeppaclientapiCollectionResponseZeppaEventToUserRelationship.h"
#import "GTLZeppaclientapiCollectionResponseZeppaNotification.h"
#import "GTLZeppaclientapiCollectionResponseZeppaUserInfo.h"
#import "GTLZeppaclientapiCollectionResponseZeppaUserToUserRelationship.h"
#import "GTLZeppaclientapiDeviceInfo.h"
#import "GTLZeppaclientapiEventComment.h"
#import "GTLZeppaclientapiEventTag.h"
#import "GTLZeppaclientapiEventTagFollow.h"
#import "GTLZeppaclientapiInviteGroup.h"
#import "GTLZeppaclientapiKey.h"
#import "GTLZeppaclientapiPhotoInfo.h"
#import "GTLZeppaclientapiZeppaEvent.h"
#import "GTLZeppaclientapiZeppaEventToUserRelationship.h"
#import "GTLZeppaclientapiZeppaFeedback.h"
#import "GTLZeppaclientapiZeppaNotification.h"
#import "GTLZeppaclientapiZeppaUser.h"
#import "GTLZeppaclientapiZeppaUserInfo.h"
#import "GTLZeppaclientapiZeppaUserToUserRelationship.h"

#import "GTLQueryZeppaclientapi.h"
#import "GTLServiceZeppaclientapi.h"
