/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseZeppaEventToUserRelationship.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseZeppaEventToUserRelationship (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseZeppaEventToUserRelationship.h"

#import "GTLZeppaclientapiZeppaEventToUserRelationship.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseZeppaEventToUserRelationship
//

@implementation GTLZeppaclientapiCollectionResponseZeppaEventToUserRelationship
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiZeppaEventToUserRelationship class]
  };
  return map;
}

@end
