/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLZeppaclientapiCollectionResponseDeviceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   zeppaclientapi/v1
// Description:
//   This is an API
// Classes:
//   GTLZeppaclientapiCollectionResponseDeviceInfo (0 custom class methods, 2 custom properties)

#import "GTLZeppaclientapiCollectionResponseDeviceInfo.h"

#import "GTLZeppaclientapiDeviceInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLZeppaclientapiCollectionResponseDeviceInfo
//

@implementation GTLZeppaclientapiCollectionResponseDeviceInfo
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLZeppaclientapiDeviceInfo class]
  };
  return map;
}

@end
